### ISSUE TITLE
Optimise simialrity metrics 

### ISSUE THREAD

**Issue by Chinmay26** [usc-isi-i2/rltk#10]
For [Jaccard similarity](https://github.com/usc-isi-i2/rltk/blob/master/rltk/similarity/jaccard.py), we can calculate union length / intersection length from De-Morgan's laws. There is no need to perform another set operation. This optimization saves around ~60s on 100K records computations.

Better to inspect other similarity metrics for other code optimizations.

**Comment by GreatYYX** [comment]
Good idea.
```
inter_len=len(s1&s2)
return float(inter_len) / (len(s1)+len(s2)-inter_len)
```

**Comment by GreatYYX** [comment]
implemented in https://github.com/usc-isi-i2/rltk/commit/29e6099f3710a396a4f2a78a6e27b97024fd7ef2
