### ISSUE TITLE
Needleman Wunsch Similarity is returning an error

### ISSUE THREAD

**Issue by rijulvohra** [usc-isi-i2/rltk#39]
I am trying to compute the needleman wunsch similarity using RLTK. But I am receiving an error. The description of the error can be seen in the attached screenshot.

<img width="1072" alt="Screen Shot 2021-05-07 at 1 01 06 PM" src="https://user-images.githubusercontent.com/19925199/117502527-7caffa80-af34-11eb-9d4b-c1c31de01ae1.png">

**Comment by rijulvohra** [comment]
ok, thanks @GreatYYX

**Comment by GreatYYX** [comment]
Fix is in release 2.0.0a16.
